language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
#  - osx

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt update ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install libzbar-dev ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -s /usr/lib/x86_64-linux-gnu/libzbar.so /usr/lib ; fi

matrix:
  include:
#    - rust: stable
#      os: linux
#      env: TARGET=x86_64-unknown-linux-musl
#      install: rustup target add $TARGET
#      script: cargo test --target $TARGET
#    - rust: beta
#      os: linux
#      env: TARGET=x86_64-unknown-linux-musl
#      install: rustup target add $TARGET
#      script: cargo test --target $TARGET
#    - rust: nightly
#      os: linux
#      env: TARGET=x86_64-unknown-linux-musl
#      install: rustup target add $TARGET
#      script: cargo test --target $TARGET
# arb change
